### ISSUE TITLE
Dearray step fails on exemplar-002

### ISSUE THREAD

**Issue by MargotCh** [labsyspharm/mcmicro-nf#329]
When running the mcmicro pipeline on the exemplar-002 data the dearraying doesn't work. This is the error that shows up:

`Error executing process > 'dearray:coreograph (1)'

Caused by:
  Process `dearray:coreograph (1)` terminated with an error exit status (137)

Command executed:

  python /app/UNetCoreograph.py       --imagePath exemplar-002.ome.tif --outputPath .

Command exit status:
  137

Command output:
  loading data
  loading data
  loading data
  0.09
  0.09
  Model restored.
  Inference...
  4 cores detected!

Command error:
  2021-10-21 12:53:53.557598: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
  .command.sh: line 2:     8 Killed                  python /app/UNetCoreograph.py --imagePath exemplar-002.ome.tif --outputPath .`

Im working on a macOS version 11.6. Is there anything I did wrong or is it a general issue?

**Comment by clarenceyapp** [comment]
Hi @MargotCh 
It appears that Coreograph identified that there are 4 cores in this TMA but could have ran out of memory when exporting each core.

How much RAM does your computer have?

How many channels and cores does your sample have?

Thanks.

**Comment by ArtemSokolov** [comment]
Hi @MargotCh 

Thanks for reaching out. Exit status 137 together with a `Killed` message usually indicate an out-of-memory situation.

I believe Docker Desktop on Mac OS X is allowed to use 2GB by default. You will find this setting in the [Preferences > Resources menu](https://docs.docker.com/desktop/mac/#resources)? I suggest increasing this value to at least 7GB and re-running the pipeline.

**Comment by MargotCh** [comment]
Hi, 
thank you both for your quick responses.

My laptop has 8GB RAM and I believe the exemplar-002 data has 4 cores and a total of 40 channels. 

I'll change the docker settings and try to run it again and come back with the results.

**Comment by MargotCh** [comment]
It works now. Thanks for the help!

**Comment by ArtemSokolov** [comment]
Excellent! Great to hear it.
